name: example_CI

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted
    environment: Labo0
    env:
      RUNNER_TOOL_CACHE: /Users/bradleysanchez/toolcache
      ACTIONS_STEP_DEBUG: true
    steps:
      - name: Checkout dépot
        uses: actions/checkout@v4

      - name: Debug RUNNER_TOOL_CACHE
        run: |
          echo "RUNNER_TOOL_CACHE is set to $RUNNER_TOOL_CACHE"
          ls -ld $RUNNER_TOOL_CACHE || echo "Directory does not exist"

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.9'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Tests
        working-directory: src
        run: |
          python -m pytest

      - name: Déploiement via SSH
        run: |
          # Install SSH client (macOS)
          brew install openssh

          if [ -z "${{ secrets.SSH_SERVER_HOST }}" ]; then
            echo "ERROR: SSH_SERVER_HOST secret is not set or empty"
            exit 1
          else
            echo "SSH_SERVER_HOST is set"
          fi
          
          # Setup SSH key
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # Add server to known hosts
          ssh-keyscan -H ${{ secrets.SSH_SERVER_HOST }} >> ~/.ssh/known_hosts
          
          # Deploy via SSH
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_SERVER_HOST }} << 'EOF'
            cd log430-a25-labo0
            git pull origin main
          EOF