name: example_CI

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted
    environment: Labo0
    steps:
      - name: Checkout dépot
        uses: actions/checkout@v4

      # - name: Installer Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.11' 
      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Tests
        working-directory: src
        run: |
          python -m pytest

      - name: Déploiement via SSH
        env:
           VM_HOST: ${{ secrets.SSH_SERVER_HOST }}
           VM_PASSWORD: ${{ secrets.SSH_PRIVATE_KEY}}
        run: |
          arch -arm64 brew install sshpass

          echo "$VM_PASSWORD" > password_file
          chmod 600 password_file

          arch -arm64 sshpass -f password_file ssh -o StrictHostKeyChecking=no log430@$VM_HOST << 'EOF'
          mkdir -p ~/my-app
          cd ~/my-app
          if [ -d ".git" ]; then
            git reset --hard
            git pull
          else
            git clone https://github.com/G00dBunny/log430-a25-labo0.git
          fi
          EOF

          rm password_file

      
         